language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php -dxdebug.coverage_enable=1 vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --whitelist src --no-configuration tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
