language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php -dxdebug.coverage_enable=1 vendor/bin/phpunit --coverage-clover=coverage.clover --whitelist /home/pinchuk/PhpstormProjects/lawyers/minjust/src --no-configuration /home/pinchuk/PhpstormProjects/lawyers/minjust/tests
